config/routes.rb
Rails.application.routes.draw do
  resources :invitations do
    collection do
      get :generate
      post :redeem
    end
  end
  resources :tenants
  resources :subscriptions do
    collection do
      get :manage
    end
  end
  resources :plans
  resources :tasks
  resources :cards
  resources :boards
  resources :organizations
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}

  root to: 'boards#index'
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :cards
  belongs_to :organization, optional: true
  belongs_to :user

  validates_presence_of :name
end

app/controllers/boards_controller.rb
class BoardsController < HomeController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  # GET /boards
  # GET /boards.json
  def index
    @my_boards = current_user.boards
    @organization_boards = current_user.organization&.boards
  end
  # GET /boards/new
  def new
    @board = Board.new
  end

  def show

  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    @board.organization_id = current_user.organization_id
    # update subscription
    subscription = current_user.subscription || current_user.organization.subscription
    Subscription.update(subscription.id, num_of_board: subscription.num_of_board + 1)
    respond_to do |format|
      if @board.save
        format.html { redirect_to root_path, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def board_params
    params.require(:board).permit(:name, :organization_id, :user_id)
  end

  def user_params
    params.require(:board).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_boards_view.html.erb
<div>
  <div class="board-name">
    <span><%= board.name %></span>
    <span class="board-add-link board-button"><%= link_to 'Add Card', new_card_path(board_id: board.id) %></span>
  </div>
  <div class="board-cards">
    <% board.cards.last(5).each do |card| %>
      <div class="board-card">
        <span style="font-weight: bold;">Title:</span>
        <span class="card-name"><%= card.name %></span>
        <span style="font-weight: bold;"> | Progress:</span>
        <span class="task-number"><%= card.tasks.where(completed: true).count %>/<%= card.tasks.count %></span>
        <span class="board-button"><%= link_to 'Add Task', new_task_path(card_id: card.id) %></span>
        <span class="board-button"><%= link_to 'Task List', tasks_path(card_id: card.id) %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
      <ul>
        <% board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>
</br>
</br>
<h3>My Name: <%= current_user.name %></h3>
<h3>My Organization: <%= current_user.organization&.name || 'NA' %></h3>
<h3>My Boards</h3>
<div class="board">
  <% @my_boards.each do |board| %>
    <%= render 'boards_view', board: board %>
  <% end %>
</div>
</br>
</br>
<%if current_user.organization?%>
  <h3>Organization Boards</h3>
  <div class="board">
    <% @organization_boards&.each do |board| %>
      <%= render 'boards_view', board: board %>
    <% end %>
  </div>
<% end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>